### PR TITLE
Code Cleaning: Format with google style and fix errors from linting results

### PR DESCRIPTION
**Pull request by chrishkchris**
I have formatted the python code according to google style using yapf
https://github.com/nusdbsystem/singa-easy/wiki/Development-Guide

### CODE REVIEW

**Comment by chrishkchris** [comment]
I followed the .pylintrc in singa-easy

while ignore one more linting rule:
too-many-format-args, # sometime we have many format args when printing the log

**Comment by chrishkchris** [comment]
ready for review/merge

**Comment by chrishkchris** [comment]
Combine all the commits into 2 commits. Ready for review/merge.

**Comment by nudles** [comment]
did you fix anything manually? or all is done by the auto-format tool yapf?

**Comment by chrishkchris** [comment]
> did you fix anything manually? or all is done by the auto-format tool yapf?

1. Firstly, I used the yapf (need to config with google style) to format
2. Remove the errors from the results of linting, e.g. 
https://github.com/nusdbsystem/singa-auto/blob/master/examples/models/pos_tagging/CRFClf.py#L56
it cannot find self.c1 when it is inside the _knobs, so we need to get the variable from _knobs

**Pull request merged**
