### PR TITLE
PR for issue #133 & issue #136

### PR DESCRIPTION
**Pull request by arielclj**
Commented out prediction button and amended post request URL for predictions

### CODE REVIEW

**Comment by chrishkchris** [comment]
@arielclj FYI, there are two prediction buttons to be commented out
b1
b2

**Comment by arielclj** [comment]
@chrishkchris Removed both buttons as requested. Code changes were tested locally.

**Comment by chrishkchris** [comment]
When you do UI change, maybe you can get some printscreen that can show the result, thanks

**Comment by arielclj** [comment]
SS
@chrishkchris Attached screenshot, as requested.

**Comment by chrishkchris** [comment]
then should be ready for merge

**Comment by arielclj** [comment]
SS3
Uploaded PR to include refinements issue #136 

Main amendments:
- Removed 0-pointers in PlotManager.js 
- Split log data & rendering of charts by data in TrialDetails.js

**Comment by arielclj** [comment]
Tested on Panda server:
for issue #136 
SS4

for issue #133 
SS5

**Comment by arielclj** [comment]
SS6
Tested locally:
for issue #136 - trial job with >1 epoch plotted. Epoch 0 is not plotted on both graphs.

**Comment by chrishkchris** [comment]
thanks, it looks correct now. 

Ready for merge

**Pull request merged**
